# **Import Libraries**

In [1]:
# Import Libraries
import pickle
import pandas as pd

# **Import Model**

In [2]:
# Load model that has already been created
with open('best_model.pkl', 'rb') as file_1: 
    model = pickle.load(file_1)

# **Made New Dataframe**

In [3]:
new_data = { 'id': [121, 211, 322],
            'age' : [20000,50827,9219],
            'gender': [1,1,2],
            'height': [175,165,170],
            'weight': [70,80,75],
            'ap_hi': [120,130,125],
            'ap_lo': [80,90,85],
            'cholesterol': [1,2,1],
            'gluc': [1,2,1],
            'smoke': [0,1,0],
            'alco' : [0,1,0],
            'active': [0,1,1],
            'cardio': [0,1,1] }

new_data = pd.DataFrame(data=new_data)
new_data

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0  121  20000       1     175      70    120     80            1     1      0   
1  211  50827       1     165      80    130     90            2     2      1   
2  322   9219       2     170      75    125     85            1     1      0   

   alco  active  cardio  
0     0       0       0  
1     1       1       1  
2     0       1       1

# **Model Training**

In [4]:
predictions = model.predict(new_data)

In [5]:
new_data['cardio'] = predictions 

# **Prediction Results**

In [6]:
new_data

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0  121  20000       1     175      70    120     80            1     1      0   
1  211  50827       1     165      80    130     90            2     2      1   
2  322   9219       2     170      75    125     85            1     1      0   

   alco  active  cardio  
0     0       0       0  
1     1       1       1  
2     0       1       0

Prediksi menggunakan model berhasil dilakukan, dimana pasien dengan id 211 adalah yang seharusnya terindikasi, sedangkan pasien dengan nomor id 322 adalah yang bukan terindikasi.